import type { Product } from "./types";

export const products: Product[] = [
  {
    slug: "core-protein",
    name: "Core Protein",
    tagline: "Grass-Fed Whey Isolate",
    purpose: "A clean, complete protein to support muscle, recovery, and everyday nutrition.",
    category: "Protein",
    goals: ["build-recover", "weight-management", "healthy-aging"],
    badges: ["Best Seller", "Daily Essential"],
    price: 54,
    subscriptionPrice: 45.9,
    servings: 30,
    rating: 4.9,
    reviewCount: 2148,
    flavors: ["Vanilla Bean", "Dutch Chocolate", "Salted Caramel", "Unflavored"],
    accent: "#B8873B",
    accentDeep: "#7E5A1F",
    benefits: [
      "22g of grass-fed whey protein isolate per serving",
      "Added digestive enzymes for easy digestion",
      "Naturally sweetened — no artificial dyes",
      "Supports muscle recovery and daily protein goals",
    ],
    floatingCallouts: [
      "22g Protein",
      "Digestive Support",
      "Recovery Support",
      "Appetite Support",
      "Daily Nutrition",
    ],
    howToUse: [
      "Add one scoop to 8–10 oz of cold water or milk.",
      "Shake or blend for 15–20 seconds.",
      "Enjoy post-workout, as a breakfast, or any time you need protein.",
    ],
    whyWeMadeIt:
      "Most protein powders are built for one goal. We built Core Protein to work for everyone — the parent grabbing a fast breakfast, the lifter chasing recovery, and the 60-year-old protecting lean muscle. Clean sourcing, honest dosing, no filler.",
    ingredients: [
      {
        name: "Whey Protein Isolate",
        amount: "24 g",
        what: "A highly filtered, fast-absorbing complete protein from grass-fed cows.",
        why: "Delivers all nine essential amino acids to support muscle and recovery.",
        purpose: "Muscle support & recovery",
      },
      {
        name: "Digestive Enzyme Blend",
        amount: "150 mg",
        what: "Protease and lactase enzymes that help break down protein and lactose.",
        why: "Helps make each serving gentle and easy on the stomach.",
        purpose: "Digestive comfort",
      },
      {
        name: "Sunflower Lecithin",
        amount: "500 mg",
        what: "A plant-derived emulsifier from sunflowers.",
        why: "Helps the powder mix smoothly without clumping.",
        purpose: "Mixability",
      },
      {
        name: "Himalayan Sea Salt",
        amount: "80 mg",
        what: "Naturally sourced mineral salt.",
        why: "Balances flavor and replenishes electrolytes lost in sweat.",
        purpose: "Flavor & electrolytes",
      },
    ],
    supplementFacts: [
      { label: "Calories", amount: "120" },
      { label: "Total Fat", amount: "1.5 g", dv: "2%" },
      { label: "Total Carbohydrate", amount: "3 g", dv: "1%" },
      { label: "Protein", amount: "22 g", dv: "44%" },
      { label: "Calcium", amount: "140 mg", dv: "11%" },
      { label: "Sodium", amount: "130 mg", dv: "6%" },
    ],
    faqs: [
      {
        q: "Is Core Protein good for weight management?",
        a: "Protein helps you feel full and supports lean muscle, both of which are helpful when managing weight. Each serving is 120 calories with 22g of protein.",
      },
      {
        q: "Will it upset my stomach?",
        a: "We include a digestive enzyme blend and use whey isolate, which is lower in lactose. Many customers who avoid other proteins tolerate Core Protein well.",
      },
      {
        q: "Is it third-party tested?",
        a: "Yes. Every batch is tested by an independent lab for purity and label accuracy.",
      },
    ],
  },
  {
    slug: "core-energy",
    name: "Core Energy",
    tagline: "Sustained Clean Energy",
    purpose: "Smooth, focused energy without the crash — for training and long days.",
    category: "Performance",
    goals: ["energy-performance", "daily-wellness"],
    badges: ["Performance", "Customer Favorite"],
    price: 42,
    subscriptionPrice: 35.7,
    servings: 30,
    rating: 4.8,
    reviewCount: 1372,
    flavors: ["Wild Berry", "Citrus Splash", "Green Apple"],
    accent: "#C06A2C",
    accentDeep: "#8A4718",
    benefits: [
      "Balanced caffeine from green tea and coffee fruit",
      "L-theanine for calm, focused energy",
      "Electrolytes to support hydration",
      "No jitters, no sugar crash",
    ],
    floatingCallouts: [
      "Clean Caffeine",
      "L-Theanine Focus",
      "Electrolytes",
      "Zero Sugar",
      "No Crash",
    ],
    howToUse: [
      "Mix one scoop with 12–16 oz of cold water.",
      "Take 20–30 minutes before training or your day.",
      "Start with half a scoop to assess tolerance.",
    ],
    whyWeMadeIt:
      "Energy shouldn't cost you a crash. We paired a moderate dose of natural caffeine with L-theanine and electrolytes to deliver energy that feels smooth and clean — appropriate whether you're heading to the gym or into a meeting.",
    ingredients: [
      {
        name: "Natural Caffeine",
        amount: "150 mg",
        what: "Caffeine sourced from green tea and coffee fruit.",
        why: "Supports alertness and physical performance.",
        purpose: "Energy & focus",
      },
      {
        name: "L-Theanine",
        amount: "200 mg",
        what: "An amino acid found in tea leaves.",
        why: "Pairs with caffeine to promote calm, steady focus.",
        purpose: "Smooth focus",
      },
      {
        name: "Electrolyte Blend",
        amount: "310 mg",
        what: "Sodium, potassium, and magnesium.",
        why: "Supports hydration during activity.",
        purpose: "Hydration",
      },
      {
        name: "Vitamin B12",
        amount: "500 mcg",
        what: "An essential B vitamin.",
        why: "Supports normal energy metabolism.",
        purpose: "Energy metabolism",
      },
    ],
    supplementFacts: [
      { label: "Calories", amount: "5" },
      { label: "Total Carbohydrate", amount: "1 g", dv: "<1%" },
      { label: "Sodium", amount: "180 mg", dv: "8%" },
      { label: "Vitamin B12", amount: "500 mcg", dv: "20833%" },
      { label: "Caffeine", amount: "150 mg" },
    ],
    faqs: [
      {
        q: "How much caffeine is in one serving?",
        a: "150 mg — roughly one and a half cups of coffee. We chose a moderate dose so it works for most people without feeling overwhelming.",
      },
      {
        q: "Can I take it in the afternoon?",
        a: "Because it contains caffeine, we recommend taking it at least 6 hours before bed.",
      },
    ],
  },
  {
    slug: "core-greens",
    name: "Core Greens",
    tagline: "Daily Superfood Blend",
    purpose: "Whole-food greens, fiber, and probiotics to fill the gaps in your diet.",
    category: "Wellness",
    goals: ["daily-wellness", "digestive-health", "healthy-aging"],
    badges: ["Daily Essential", "New"],
    price: 48,
    subscriptionPrice: 40.8,
    servings: 30,
    rating: 4.7,
    reviewCount: 864,
    flavors: ["Mint", "Berry", "Unflavored"],
    accent: "#1F6B57",
    accentDeep: "#124237",
    benefits: [
      "25+ whole-food greens and superfoods",
      "Prebiotic fiber and probiotics for gut health",
      "Digestive enzymes for comfortable digestion",
      "An easy daily foundation for busy schedules",
    ],
    floatingCallouts: [
      "25+ Superfoods",
      "Probiotics",
      "Prebiotic Fiber",
      "Digestive Enzymes",
      "Daily Foundation",
    ],
    howToUse: [
      "Mix one scoop into 8–12 oz of cold water.",
      "Enjoy first thing in the morning or with a meal.",
      "Can be blended into a smoothie.",
    ],
    whyWeMadeIt:
      "Even good diets miss things. Core Greens is a simple, once-a-day way to add whole-food nutrition, fiber, and gut support — without choking down a dozen pills. Approachable enough for anyone building a healthier routine.",
    ingredients: [
      {
        name: "Organic Greens Blend",
        amount: "3 g",
        what: "Spinach, kale, spirulina, chlorella, and moringa.",
        why: "Adds concentrated whole-food nutrition to your day.",
        purpose: "Daily nutrition",
      },
      {
        name: "Prebiotic Fiber",
        amount: "2 g",
        what: "Fiber from chicory root inulin.",
        why: "Feeds beneficial gut bacteria and supports regularity.",
        purpose: "Gut & digestion",
      },
      {
        name: "Probiotic Blend",
        amount: "3 Billion CFU",
        what: "Live, shelf-stable beneficial bacteria strains.",
        why: "Supports a balanced digestive system.",
        purpose: "Gut health",
      },
      {
        name: "Digestive Enzymes",
        amount: "100 mg",
        what: "A blend of amylase, protease, and lipase.",
        why: "Helps your body break down food comfortably.",
        purpose: "Digestive comfort",
      },
    ],
    supplementFacts: [
      { label: "Calories", amount: "30" },
      { label: "Total Carbohydrate", amount: "5 g", dv: "2%" },
      { label: "Dietary Fiber", amount: "2 g", dv: "7%" },
      { label: "Vitamin A", amount: "450 mcg", dv: "50%" },
      { label: "Vitamin C", amount: "45 mg", dv: "50%" },
      { label: "Iron", amount: "3 mg", dv: "17%" },
    ],
    faqs: [
      {
        q: "Does it replace vegetables?",
        a: "No — think of Core Greens as a supplement to a balanced diet, not a replacement for whole foods. It's a convenient way to add extra nutrition.",
      },
      {
        q: "Does it taste like grass?",
        a: "Our Mint and Berry flavors are light and refreshing. Most customers are pleasantly surprised.",
      },
    ],
  },
  {
    slug: "core-recover",
    name: "Core Recover",
    tagline: "Post-Workout Recovery",
    purpose: "Amino acids and electrolytes to help you bounce back and rebuild.",
    category: "Recovery",
    goals: ["build-recover", "energy-performance"],
    badges: ["Performance"],
    price: 44,
    subscriptionPrice: 37.4,
    servings: 30,
    rating: 4.8,
    reviewCount: 967,
    flavors: ["Watermelon", "Blue Raspberry", "Mango"],
    accent: "#2B6E74",
    accentDeep: "#184A50",
    benefits: [
      "Full-spectrum EAAs including 5g of BCAAs",
      "Electrolytes for rehydration",
      "Supports muscle repair after training",
      "Light, refreshing, and easy to sip",
    ],
    floatingCallouts: [
      "9 Essential Aminos",
      "5g BCAAs",
      "Electrolytes",
      "Muscle Repair",
      "Rehydration",
    ],
    howToUse: [
      "Mix one scoop with 12–16 oz of cold water.",
      "Sip during or immediately after your workout.",
      "Great for hot days and long training sessions.",
    ],
    whyWeMadeIt:
      "Recovery is where progress actually happens. Core Recover delivers the essential amino acids your muscles use to rebuild, plus electrolytes to replace what you sweat out — in a formula light enough to sip all session.",
    ingredients: [
      {
        name: "Essential Amino Acids",
        amount: "7 g",
        what: "All nine essential amino acids your body can't make on its own.",
        why: "Provides the building blocks for muscle repair.",
        purpose: "Muscle recovery",
      },
      {
        name: "BCAA Blend (2:1:1)",
        amount: "5 g",
        what: "Leucine, isoleucine, and valine.",
        why: "Supports muscle protein synthesis after exercise.",
        purpose: "Rebuilding",
      },
      {
        name: "Electrolyte Complex",
        amount: "500 mg",
        what: "Sodium, potassium, and magnesium.",
        why: "Replaces minerals lost through sweat.",
        purpose: "Hydration",
      },
      {
        name: "Coconut Water Powder",
        amount: "250 mg",
        what: "Dehydrated coconut water.",
        why: "A natural source of hydration-supporting minerals.",
        purpose: "Rehydration",
      },
    ],
    supplementFacts: [
      { label: "Calories", amount: "10" },
      { label: "Total Carbohydrate", amount: "1 g", dv: "<1%" },
      { label: "Sodium", amount: "220 mg", dv: "10%" },
      { label: "Potassium", amount: "180 mg", dv: "4%" },
      { label: "EAAs", amount: "7 g" },
    ],
    faqs: [
      {
        q: "When should I take Core Recover?",
        a: "During or right after your workout is ideal, but it works any time you want amino acids and hydration.",
      },
    ],
  },
  {
    slug: "core-burn",
    name: "Core Burn",
    tagline: "Metabolism & Appetite Support",
    purpose: "A thoughtful blend to support metabolism and healthy appetite.",
    category: "Weight Management",
    goals: ["weight-management", "energy-performance"],
    badges: ["Customer Favorite"],
    price: 46,
    subscriptionPrice: 39.1,
    servings: 30,
    rating: 4.6,
    reviewCount: 1105,
    flavors: ["Peach Mango", "Strawberry Lemonade"],
    accent: "#A6472A",
    accentDeep: "#732F19",
    benefits: [
      "Supports a healthy metabolism",
      "Fiber and chromium for appetite support",
      "Green tea extract for gentle energy",
      "No harsh stimulants or crash",
    ],
    floatingCallouts: [
      "Metabolism Support",
      "Appetite Support",
      "Gentle Energy",
      "Fiber Blend",
      "No Crash",
    ],
    howToUse: [
      "Mix one scoop with 12 oz of cold water.",
      "Take once daily, ideally before a meal.",
      "Pair with a balanced diet and regular movement.",
    ],
    whyWeMadeIt:
      "Weight management is personal and rarely simple. Core Burn skips the harsh stimulants and gimmicks in favor of a measured blend that supports metabolism and appetite — meant to complement your habits, not replace them.",
    ingredients: [
      {
        name: "Green Tea Extract",
        amount: "400 mg",
        what: "Standardized for EGCG, a natural plant compound.",
        why: "Provides gentle energy and antioxidant support.",
        purpose: "Metabolism support",
      },
      {
        name: "Soluble Fiber Blend",
        amount: "3 g",
        what: "Fiber from glucomannan and acacia.",
        why: "Helps you feel full and supports appetite control.",
        purpose: "Appetite support",
      },
      {
        name: "Chromium Picolinate",
        amount: "200 mcg",
        what: "An essential trace mineral.",
        why: "Supports normal macronutrient metabolism.",
        purpose: "Metabolic support",
      },
      {
        name: "L-Carnitine",
        amount: "500 mg",
        what: "An amino acid derivative.",
        why: "Involved in the body's energy production.",
        purpose: "Energy metabolism",
      },
    ],
    supplementFacts: [
      { label: "Calories", amount: "15" },
      { label: "Total Carbohydrate", amount: "3 g", dv: "1%" },
      { label: "Dietary Fiber", amount: "3 g", dv: "11%" },
      { label: "Chromium", amount: "200 mcg", dv: "571%" },
      { label: "Caffeine", amount: "90 mg" },
    ],
    faqs: [
      {
        q: "Is this a substitute for diet and exercise?",
        a: "No. Core Burn is designed to support a healthy lifestyle, not replace it. The best results come from pairing it with balanced nutrition and regular movement.",
      },
    ],
  },
  {
    slug: "core-vitality",
    name: "Core Vitality",
    tagline: "Daily Multivitamin",
    purpose: "A complete daily multivitamin built for real, modern nutrition gaps.",
    category: "Wellness",
    goals: ["daily-wellness", "healthy-aging"],
    badges: ["Daily Essential", "Best Seller"],
    price: 38,
    subscriptionPrice: 32.3,
    servings: 30,
    rating: 4.9,
    reviewCount: 1789,
    flavors: ["Capsule"],
    accent: "#3C6079",
    accentDeep: "#264656",
    benefits: [
      "23 essential vitamins and minerals",
      "Bioavailable, easy-to-absorb forms",
      "Includes Vitamin D3, B12, and magnesium",
      "One clean daily foundation",
    ],
    floatingCallouts: [
      "23 Nutrients",
      "Vitamin D3",
      "B-Complex",
      "Magnesium",
      "Daily Foundation",
    ],
    howToUse: [
      "Take two capsules daily with a meal.",
      "Best taken in the morning with water.",
      "Consistency matters — take daily for best results.",
    ],
    whyWeMadeIt:
      "A multivitamin should be a dependable foundation, not a mystery blend. Core Vitality uses well-researched, bioavailable nutrient forms at honest doses — the kind of everyday support that suits a 25-year-old and a 65-year-old alike.",
    ingredients: [
      {
        name: "Vitamin D3",
        amount: "50 mcg (2000 IU)",
        what: "The active, sunshine form of vitamin D.",
        why: "Supports bone health and immune function.",
        purpose: "Bone & immune support",
      },
      {
        name: "Methylated B-Complex",
        amount: "Full spectrum",
        what: "Active forms of the eight B vitamins.",
        why: "Supports energy metabolism and nervous system health.",
        purpose: "Energy & nerves",
      },
      {
        name: "Magnesium Glycinate",
        amount: "150 mg",
        what: "A gentle, well-absorbed form of magnesium.",
        why: "Supports muscle, nerve, and sleep function.",
        purpose: "Relaxation & recovery",
      },
      {
        name: "Zinc & Selenium",
        amount: "11 mg / 55 mcg",
        what: "Essential trace minerals.",
        why: "Support immune health and antioxidant defense.",
        purpose: "Immune support",
      },
    ],
    supplementFacts: [
      { label: "Vitamin D3", amount: "50 mcg", dv: "250%" },
      { label: "Vitamin C", amount: "90 mg", dv: "100%" },
      { label: "Vitamin B12", amount: "250 mcg", dv: "10417%" },
      { label: "Magnesium", amount: "150 mg", dv: "36%" },
      { label: "Zinc", amount: "11 mg", dv: "100%" },
    ],
    faqs: [
      {
        q: "Can I take it with other Total Core products?",
        a: "Yes. Core Vitality is designed as a foundation and pairs well with our protein, greens, and performance formulas.",
      },
    ],
  },
  {
    slug: "core-collagen",
    name: "Core Collagen",
    tagline: "Joints, Skin & Hair",
    purpose: "Grass-fed collagen peptides to support joints, skin, and healthy aging.",
    category: "Wellness",
    goals: ["healthy-aging", "build-recover", "daily-wellness"],
    badges: ["Customer Favorite"],
    price: 40,
    subscriptionPrice: 34,
    servings: 30,
    rating: 4.8,
    reviewCount: 1023,
    flavors: ["Unflavored", "Vanilla", "Chocolate"],
    accent: "#B07A55",
    accentDeep: "#855237",
    benefits: [
      "10g grass-fed collagen peptides",
      "Types I & III for skin and joints",
      "Added vitamin C for collagen synthesis",
      "Dissolves clear in hot or cold drinks",
    ],
    floatingCallouts: [
      "10g Collagen",
      "Types I & III",
      "Vitamin C",
      "Joint Support",
      "Skin & Hair",
    ],
    howToUse: [
      "Stir one scoop into coffee, tea, or a smoothie.",
      "Dissolves clear and tasteless in the unflavored version.",
      "Use daily for best long-term results.",
    ],
    whyWeMadeIt:
      "As we age, our natural collagen declines. Core Collagen makes it effortless to add high-quality peptides to your routine — supporting the joints, skin, and hair that carry you through an active life at any age.",
    ingredients: [
      {
        name: "Collagen Peptides",
        amount: "10 g",
        what: "Hydrolyzed Type I & III collagen from grass-fed sources.",
        why: "Provides the amino acids your body uses to build connective tissue.",
        purpose: "Joint & skin support",
      },
      {
        name: "Vitamin C",
        amount: "90 mg",
        what: "An essential antioxidant vitamin.",
        why: "Required for your body's own collagen production.",
        purpose: "Collagen synthesis",
      },
      {
        name: "Hyaluronic Acid",
        amount: "40 mg",
        what: "A naturally occurring hydrating compound.",
        why: "Supports skin moisture and joint cushioning.",
        purpose: "Hydration & cushioning",
      },
      {
        name: "Biotin",
        amount: "2500 mcg",
        what: "A B vitamin also known as B7.",
        why: "Supports healthy hair, skin, and nails.",
        purpose: "Hair & nails",
      },
    ],
    supplementFacts: [
      { label: "Calories", amount: "40" },
      { label: "Protein", amount: "9 g", dv: "18%" },
      { label: "Vitamin C", amount: "90 mg", dv: "100%" },
      { label: "Biotin", amount: "2500 mcg", dv: "8333%" },
    ],
    faqs: [
      {
        q: "How long until I see results?",
        a: "Collagen works gradually. Most customers use it consistently for 8–12 weeks to notice benefits for skin, hair, and joint comfort.",
      },
    ],
  },
  {
    slug: "core-sleep",
    name: "Core Sleep",
    tagline: "Nighttime Recovery",
    purpose: "A gentle, non-habit-forming blend to support restful sleep and recovery.",
    category: "Recovery",
    goals: ["daily-wellness", "healthy-aging", "build-recover"],
    badges: ["New"],
    price: 39,
    subscriptionPrice: 33.15,
    servings: 30,
    rating: 4.7,
    reviewCount: 612,
    flavors: ["Berry", "Unflavored"],
    accent: "#5E4A78",
    accentDeep: "#3E3054",
    benefits: [
      "Magnesium and glycine for relaxation",
      "A low, gentle dose of melatonin",
      "L-theanine to help calm the mind",
      "Non-habit-forming, wake up refreshed",
    ],
    floatingCallouts: [
      "Magnesium",
      "Low-Dose Melatonin",
      "L-Theanine",
      "Glycine",
      "Restful Sleep",
    ],
    howToUse: [
      "Mix one scoop with 6–8 oz of water.",
      "Take 30–45 minutes before bed.",
      "Create a calm, screen-free wind-down routine.",
    ],
    whyWeMadeIt:
      "Recovery doesn't stop when you leave the gym. Core Sleep supports the deep rest your body rebuilds on — with a gentle, low-dose formula designed to help you fall asleep and wake up clear, not groggy.",
    ingredients: [
      {
        name: "Magnesium Glycinate",
        amount: "200 mg",
        what: "A gentle, absorbable form of magnesium.",
        why: "Supports muscle relaxation and calm.",
        purpose: "Relaxation",
      },
      {
        name: "L-Theanine",
        amount: "200 mg",
        what: "A calming amino acid from tea.",
        why: "Helps quiet a busy mind before bed.",
        purpose: "Mental calm",
      },
      {
        name: "Glycine",
        amount: "3 g",
        what: "An amino acid involved in sleep quality.",
        why: "Supports the body's natural transition to rest.",
        purpose: "Sleep quality",
      },
      {
        name: "Melatonin",
        amount: "1 mg",
        what: "A hormone your body produces naturally.",
        why: "A low dose helps signal that it's time to sleep.",
        purpose: "Sleep timing",
      },
    ],
    supplementFacts: [
      { label: "Calories", amount: "10" },
      { label: "Magnesium", amount: "200 mg", dv: "48%" },
      { label: "Glycine", amount: "3 g" },
      { label: "Melatonin", amount: "1 mg" },
    ],
    faqs: [
      {
        q: "Will I feel groggy in the morning?",
        a: "We use a low 1 mg dose of melatonin specifically to help you rest without the morning grogginess that higher doses can cause.",
      },
    ],
  },
];

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);

export const getProductsByGoal = (goalId: string) =>
  products.filter((p) => p.goals.includes(goalId as never));

export const bestSellers = () =>
  products.filter((p) => p.badges.includes("Best Seller"));

export const featuredProducts = () =>
  products.filter((p) =>
    p.badges.some((b) =>
      ["Best Seller", "Customer Favorite", "New", "Daily Essential"].includes(b)
    )
  );
